### ISSUE TITLE
Is it possible to use buildbuddy to build go apps using the go toolchain?

### ISSUE THREAD

**Issue by jabalsad** [buildbuddy-io/buildbuddy#2109]
Hi,

I've been playing around with buildbuddy, but unfortunately I'm not super experienced with Bazel yet.

I'm using the [rules_go](https://github.com/bazelbuild/rules_go) go toolchain to build my application. When trying to use Buildbuddy's RBE feature, I can't quite seem to get the builds to work because the go toolchain cannot be resolved.

Is it possible to configure it to use the go toolchain? According to [this document](https://www.buildbuddy.io/docs/rbe-setup/#toolchains) it seems like only C and Java is supported. Is this correct? I've tried launching using a go docker container, but no success.

Thanks.

**Comment by siggisim** [comment]
Hey @jabalsad - go is very much supported. BuildBuddy itself is built in Go and we use remote build execution heavily.

Here's what our .bazelrc looks like: https://github.com/buildbuddy-io/buildbuddy/blob/master/.bazelrc#L25

Are you building from a Mac host or a Linux host? What's the error message you're seeing?

**Comment by jabalsad** [comment]
Thanks for the fast response! I followed the RBE tutorial on the docs, and got this error:

```
› bazel build //... --config=remote
INFO: Invocation ID: 1d71648b-b550-4d19-a607-6bf867fdcb89
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/1d71648b-b550-4d19-a607-6bf867fdcb89
INFO: Build options --extra_execution_platforms and --platforms have changed, discarding analysis cache.
ERROR: /Users/jleroux/w/stedi/go/src/github.com/stedi/auth-go/pkg/auth/BUILD.bazel:3:11: While resolving toolchains for target //pkg/auth:auth: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//pkg/auth:auth' failed; build aborted:
INFO: Elapsed time: 0.326s
INFO: 0 processes.
INFO: Streaming build results to: https://app.buildbuddy.io/invocation/1d71648b-b550-4d19-a607-6bf867fdcb89
FAILED: Build did NOT complete successfully (0 packages loaded, 243 targets configured)
```

I'll take a peek at your bazelrc to see what I'm missing.

**Comment by siggisim** [comment]
The issue here is likely that you're using a mac host, but trying to run on Linux RBE executors (our free tier doesn't include Mac executors).

Here's a command that works to test BuildBuddy from a Mac host on linux executors:
```
bazel test //... --remote_executor=remote.buildbuddy.io --host_cpu=k8 --cpu=k8 --crosstool_top=@buildbuddy_toolchain//:ubuntu1604_cc_toolchain_suite --host_platform=@buildbuddy_toolchain//:platform_linux --extra_toolchains=@buildbuddy_toolchain//:ubuntu1604_cc_toolchain --jobs=100
```

In order to support this targeting of linux machines - you'll also need to download the linux go sdk in your WORKSPACE file like this: https://github.com/buildbuddy-io/buildbuddy/blob/master/WORKSPACE#L34

This building on linux executors from a mac host works for some situations, but with that command - the target artifacts will be built for linux (which doesn't really matter because it's a test command). It's possible to fiddle around with this, but we typically recommend using mac executors if your bazel host is a mac for the smoothest experience.
