### ISSUE TITLE
What is the scope of the '100 GB of cache transfer' in the personal plan?

### ISSUE THREAD

**Issue by typesanitizer** [buildbuddy-io/buildbuddy#2354]
I'm exploring using BuildBuddy for a couple of OSS projects, for which the caches are in the range of 1-2.5 GB per job.

Could you clarify the following:
- Does the 100 GB cover storage (e.g. GitHub Actions has 10GB storage for free) or purely transfer?
- Is the 100 GB of transfer a 1 time limit, or does it renew (does it apply per-invocation/per fixed duration of time/something else)?

Thanks! (Also, I like buildbuddy.io website's design, it feels modern but it's still fast.)

**Comment by siggisim** [comment]
Hey @typesanitizer - thanks for reaching out!

The 100GB limit on our free tier covers purely transfer. The limit renews monthly - i.e. 100GB of cache transfer per month.

There are Bazel flags you can use to reduce your cache transfer per build, like `--remote_download_minimal` or `--remote_download_toplevel`.

We're not super strict on enforcing this limit, particularly for OSS projects (see **What happens if I go over my limit?** at the bottom of https://www.buildbuddy.io/pricing). As long as you don't go way above the monthly limit, you should be alright.
