### ISSUE TITLE
Allow more flexibility with TargetSelector in Build Results API

### ISSUE THREAD

**Issue by Qinusty** [buildbuddy-io/buildbuddy#27]
I've been looking through some of the API documentation this afternoon for the Build Results API and noticed that the TargetSelector is missing any option to query by label.

[TargetSelector](https://github.com/buildbuddy-io/buildbuddy/blob/master/proto/api/v1/target.proto#L56) requires a invocation ID, would it make sense to extend this to allow querying by label and remove the invocation_id requirement? This would allow for querying of potentially troublesome targets across many invocations.

Keep up the great work!

**Comment by siggisim** [comment]
Hey @Qinusty - target level filtering is high on our roadmap.

Currently, everything is stored and scoped at the invocation level. Once we've got the target metadata parsed and captured in a format that's easy to query across invocations, we'll definitely expose this on the API side as well.

Keep the suggestions coming!

**Comment by siggisim** [comment]
TargetSelector now has the ability to filter by label thanks to https://github.com/buildbuddy-io/buildbuddy/pull/1253

We've also made some progress in tracking targets across invocations, but this is currently limited to test targets (due to the sheer number of targets contained in some large builds). Feel free to open a separate issue for dropping the invocation_id requirement if this is still a priority for you!
