### ISSUE TITLE
Spanner integration

### ISSUE THREAD

**Issue by Jonpez2** [buildbuddy-io/buildbuddy#7569]
would you have any interest in integrating spanner into your codebase as an option to replace both redis and MySQL, thus allowing gcp-based clients to work with 100% gcp supported services?
If we also were to use xds based addressing (built into grpc and thus I expect natively supported for you) from bazel, we could end up with the ability to run across multiple clusters and even multiple regions - an incredible operational story. 

Thank you!

**Comment by siggisim** [comment]
Hey @Jonpez2 - this is a great idea, but not on our immediate roadmap.

You can use Google Cloud SQL in the meantime if you want a fully managed MySQL setup - which BuildBuddy supports: https://cloud.google.com/sql?hl=en

**Comment by Jonpez2** [comment]
Ok cool I’m glad you’re open to it. Given that spanner supports Postgres
vernacular, I _think_ it’s ‘just’ a matter of wiring through a connection,
using client libraries so we get application default credentials and
workload identity. Would you be open to a) giving me a couple of pointers
on where to look and b) being gentle when reviewing a pull request?

**Comment by Jonpez2** [comment]
FWIW, [this](https://github.com/googleapis/go-gorm-spanner) looks like it covers what we would need, with a simple spanner://{full path to your spanner database} connection string.  It doesn't seem to expose a Driver though, so the wrapping that you do [here](https://github.com/buildbuddy-io/buildbuddy/blob/master/server/util/db/db_cgo.go#L17) seems hard.

**Comment by sluongng** [comment]
> Would you be open to a) giving me a couple of pointers on where to look and b) being gentle when reviewing a pull request?

Certainly.

Here is the current DB logic https://github.com/buildbuddy-io/buildbuddy/blob/5733433b83f409bbb0ac3ebadac808b331f4765e/server/util/db/db.go#L34-L36
with multiple DB dialects that we support today (MySQL, postgres, sqlite).

So I think it's just a matter of (a) adding the new dependencies, (b) wiring up the code, and (c) setting up some tests to run against spanner-emulator to avoid regression.

As mentioned by Siggi, GCP is currently supporting both MySQL and Redis as managed services. So it might be easier to just use CloudSQL (for MySQL) and Memorystore (for Redis) instead of trying to make Spanner work.

**Comment by Jonpez2** [comment]
Thanks, that's where I got to as well.  I'll see where I can get to.
